configVersion: 3
spawnTick: 40
worldName: "lobby"
fireworkFlightDuration: 1
muteSpawnSound: true
muteExplodeSound: false
splitGroups: true
positionCount: 8

pos0:
  x: -12
  y: 87
  z: 29
pos1:
  x: -29
  y: 87
  z: -12
pos2:
  x: 12
  y: 87
  z: -29
pos3:
  x: 29
  y: 87
  z: 12
pos4:
  x: 12
  y: 87
  z: 29
pos5:
  x: -29
  y: 87
  z: 12
pos6:
  x: -12
  y: 87
  z: -29
pos7:
  x: 29
  y: 87
  z: -12
